<?php

/**
 * @file
 * Examples showing how to use some of the new JavaScript features in Drupal 8.
 */

use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * @defgroup bc_2movepeople_dashboard.module: JavaScript
 * @ingroup 2movepeople
 * @{
 *
 */

/**
 * Implements hook_theme().
 */
function bc_2movepeople_dashboard_theme() {
  return array(
    'bc_2movepeople_dashboard_accordion' => array(
      'template' => 'accordion',
      'variables' => array('title' => NULL),
    ),
    'bc_2movepeople_dashboard' => array(
      'template' => 'bc-2movepeople-dashboard',
      'variables' => array('title' => NULL,
        'user' => NULL,
        'subtitle' => NULL,
        'progression_targets' => array()),
    ),
    'bc_2movepeople_milestone_dashboard' => array(
      'template' => 'bc-2movepeople-milestone-dashboard',
      'variables' => array('title' => NULL,
        'user' => NULL,
        'subtitle' => NULL,
        'milestone_targets' => array()),
    ),
    'bc_2movepeople_dashboard_clients' => array(
      'template' => 'bc-2movepeople-dashboard-clients',
      'variables' => array('title' => NULL,
      'users' => array()),
    ),
    'bc_2movepeople_dashboard_user_overview' => array(
      'template' => 'bc-2movepeople-dashboard-user-overview',
      'variables' => array('title' => NULL,
      'user' => NULL,
      'table_progression' => NULL, 'table_milestone' => NULL),
    ),
    'bc_2movepeople_dashboard_progression_total_table' => array(
      'template' => 'bc-2movepeople-dashboard-progression-total-table',
      'variables' => array(
      'type' => 'progression',
      'table_header' => array(),
      'table_data' => array()),
    ),
    'bc_2movepeople_dashboard_user_tasks_overview' => array(
      'template' => 'bc-2movepeople-user-tasks',
      'variables' => array(
          'title' => NULL,
          'tasks' => NULL,
          'user'  => NULL
      ),
    ),
  );
}

/**
 * @} End of "defgroup bc_2movepeople_dashboard.accordion".
 */

/**
 * Implements hook_user_login().
 */
function bc_2movepeople_dashboard_user_login($account) {
    $path = '/';
    $user_roles = $account->getRoles();
    if (in_array("2mp_user", $user_roles)) {
      $path = Url::fromRoute('bc_2movepeople_dashboard_user_tasks_overview', ['user' => $account->id()])->toString();
    }  
    $response = new RedirectResponse($path);
    $response->send(); 
}
