<?php

/**
 * @file
 * Install, update, and uninstall functions for the 2Movepeople common module.
 */

use Drupal\bc_2movepeople\Form\ConfigForm;

/**
 * Remove menu from db to override them from code.
 */
function bc_2movepeople_update_8001() {
  $menu_name = 'settings-menu';
  $menu_tree = \Drupal::menuTree();
  $parameters = $menu_tree->getCurrentRouteMenuTreeParameters($menu_name);
  $tree = $menu_tree->load($menu_name, $parameters);
  foreach ($tree as $menu_item) {
    if ($menu_item->link->isDeletable()) {
      $menu_item->link->deleteLink();
    }
  }
}

/**
 * Add meeting enavle/disable setting.
 */
function bc_2movepeople_update_8901(&$sandbox) {
  $config = \Drupal::service('config.factory')->getEditable(ConfigForm::getConfigName());
  $config->set('enable_meetings', TRUE);
  $config->save();
}
