<?php

/**
 * @file
 * Contains bc_2movepeople.module.
 */
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function bc_2movepeople_form_user_form_alter(&$form, FormStateInterface $form_state) {
  $current_user = \Drupal::currentUser();
  if ($current_user->id() == 1) {
    return;
  }

  foreach (Element::children($form) as $key) {
    if (in_array($key, ['contact', 'timezone', 'language'])) {
      _bc_2movepeople_hide_field($form, $key);
    }
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function bc_2movepeople_module_implements_alter(&$implementations, $hook) {
  switch ($hook) {
    // Move our bc_2movepeople_form_user_form_alter implementation to the end of the list.
    case 'form_alter':
      if (array_key_exists('bc_2movepeople', $implementations)){
      $group = $implementations['bc_2movepeople'];
      unset($implementations['bc_2movepeople']);
      $implementations['bc_2movepeople'] = $group;
      break;
      }
  }
}

/**
 * Hide some fields in a form.
 *
 * @param array $form
 *   Nested array of form elements that comprise the form.
 * @param array $field_names
 *   Array of field names to be hidden.
 * @return void
 */
function _bc_2movepeople_hide_field(&$form, $field_names) {
  if (!is_array($field_names)) {
    $field_names = [$field_names];
  }

  foreach ($field_names as $field_name) {
    $form[$field_name]['#disabled'] = TRUE;
    $form[$field_name]['#type'] = 'hidden';
    $form[$field_name]['#access'] = FALSE;
  }
}
