<?php

/**
 * @file
 * Contains bc_2movepeople.module.
 */
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Entity\EntityTypeInterface;
/*
 * Implements hook_toolbar_alter()
 */
function bc_2movepeople_toolbar_alter(&$items) {
  $items['administration']['#attached']['library'][] = 'bc_2movepeople/toolbar-icon';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function bc_2movepeople_form_user_form_alter(&$form, FormStateInterface $form_state) {

  $form['#validate'][] = '_bc_2movepeople_user_form_validate';
  $config = \Drupal::config('bc_2movepeople.settings');
  if( !$config->get('email_required')){
    $form['account']['mail']['#required'] = 0;
  }

  $current_user = \Drupal::currentUser();
  if ($current_user->id() == 1) {
    return;
  }

  foreach (Element::children($form) as $key) {
    if (in_array($key, ['contact', 'timezone', 'language'])) {
      _bc_2movepeople_hide_field($form, $key);
    }
  }
}

/**
 * Validates submission values in the user_form form.
 */
function _bc_2movepeople_user_form_validate(array &$form, FormStateInterface $form_state) {

  //Unset mail Error when mail is empty and not requred
  $config = \Drupal::config('bc_2movepeople.settings');

  if(!($config->get('email_required')) &&  empty($form['account']['mail']['#value'])){
    // Temporarily store all form errors.
    $form_errors = $form_state->getErrors();
    unset($form_errors['mail']);
    $form_state->clearErrors();
    // Loop through and re-apply the remaining form error messages.
    foreach ($form_errors as $name => $error_message) {
      $form_state->setErrorByName($name, $error_message);
    }
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function bc_2movepeople_module_implements_alter(&$implementations, $hook) {
  switch ($hook) {
    // Move our bc_2movepeople_form_user_form_alter implementation to the end of the list.
    case 'form_alter':
      if (array_key_exists('bc_2movepeople', $implementations)){
      $group = $implementations['bc_2movepeople'];
      unset($implementations['bc_2movepeople']);
      $implementations['bc_2movepeople'] = $group;
      break;
      }
  }
}

/**
 * Hide some fields in a form.
 *
 * @param array $form
 *   Nested array of form elements that comprise the form.
 * @param array $field_names
 *   Array of field names to be hidden.
 * @return void
 */
function _bc_2movepeople_hide_field(&$form, $field_names) {
  if (!is_array($field_names)) {
    $field_names = [$field_names];
  }

  foreach ($field_names as $field_name) {
    $form[$field_name]['#disabled'] = TRUE;
    $form[$field_name]['#type'] = 'hidden';
    $form[$field_name]['#access'] = FALSE;
  }
}

/**
 * Implements hook_entity_bundle_field_info().
 */
function bc_2movepeople_entity_base_field_info_alter(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type) {
  if ($entity_type->id() != 'user') {
    return;
  }
  $fields['name']->setLabel(t('Username'));
}
