<?php

/**
 * @file
 * Contains bc_2movepeople_rate_progression.module..
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\bc_2movepeople\Form\TextSettings;

function bc_2movepeople_rate_progression_get_rates($progression_target_id, $goal_id, $status = 1) {
  $query = \Drupal::database()->select('bc_2movepeople_rate_progression', 'rates');
  $query->fields('rates', array('rate'))
    ->condition('uid', \Drupal::currentUser()->id(), '=')
    ->condition('goal_id', $goal_id, '=')
    ->condition('progression_target_id', $progression_target_id, '=')
    ->condition('status', $status)
    ->orderBy('created', 'DESC')
    ->range(0, 5);
  $result = $query->execute()->fetchAll();
  $rate_arr =  array();
  foreach ($result as $row) {
    $rate_arr[] = '[ ' . $row->rate . ' ]';
  }
  return array_reverse($rate_arr);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function bc_2movepeople_rate_progression_form_bc_2movepeople_text_settings_alter(&$form, FormStateInterface $form_state, $form_id) {
  $config = \Drupal::config(TextSettings::$config_name);
  $form['bc_2movepeople_rate_progresion'] = [
    '#type' => 'details',
    '#open' => TRUE,
    '#title' => t('Progression rate'),
  ];
  $texts = [
    'self_rates_add_title' => t('Self rates add form title'),
    'user_rates_add_title' => t('User rates add form title'),
    'rates_add_title' => t('Rates add form title'),
  ];
  foreach ($texts as $key => $label) {
    $form['bc_2movepeople_rate_progresion'][$key] = [
      '#type' => 'textfield',
      '#title' => $label,
      '#default_value' => $config->get('bc_2movepeople_rate_progresion.' . $key),
    ];

  }
}
