<?php
use Drupal\Core\Database\Database;

function bc_2movepeople_rate_progression_schema() {
  $schema['bc_2movepeople_rate_progression'] = array(
    'description' => 'This table stores goal rates',
    'fields' => array(
      'id' => array(
        'description' => 'The rate id',
        'type' => 'serial',
        'not null' => TRUE,
      ),
      'progression_target_id' => array(
        'description' => 'Node id of the progressio target',
        'type' => 'int',
        'not null' => TRUE,
      ),
      'goal_id' => array(
        'description' => 'Node id of the goal',
        'type' => 'int',
        'not null' => TRUE,
      ),
      'rate' => array(
        'description' => 'Progerssion rate',
        'type' => 'int',
        'not null' => TRUE,
      ),
      'uid' => array(
        'description' => 'The user id of the note author',
        'type' => 'int',
        'not null' => TRUE,
      ),
      'rate_autor' => array(
        'description' => 'The user id of the rate autor',
        'type' => 'int',
        'not null' => TRUE,
      ),
      'created' => array(
        'description' => 'Timestamp of when rate was created',
        'type' => 'int',
        'unsigned' => TRUE,
      ),
      'status' => array(
        'description' => 'Status of the rate',
        'type' => 'int',
      ),
    ),
    'primary key' => array('id'),
    'indexes' => array(
      'ind_goal_id' => array('goal_id'),
      'uid' => array('uid'),
    ),
  );
  return $schema;
}

/**
 * Add a rate autor id to table.
 */
function bc_2movepeople_rate_progression_update_8002(&$sandbox) {

  $spec = array(
    'description' => 'The user id who put the rate',
    'type' => 'int',
    'not null' => FALSE,
  );
  $schema = Database::getConnection()->schema();
  $schema->addField('bc_2movepeople_rate_progression', 'rate_autor', $spec);
}

/**
 * Add status column to rate table.
 */
function bc_2movepeople_rate_progression_update_8003(&$sandbox) {
  $spec = array(
    'description' => 'Status of the rate',
    'type' => 'int',
    'default' => 1,
  );
  $schema = Database::getConnection()->schema();
  $schema->addField('bc_2movepeople_rate_progression', 'status', $spec);
}
