<?php
use Drupal\Component\Utility\Html;

/**
 * Implements hook_preprocess_page().
 */
function bellcom_preprocess_page(array &$variables) {}

/**
 * Implements hook_preprocess_HOOK().
 */
function bellcom_preprocess_taxonomy_term(&$variables) {
  $term = $variables['term'];
  $view_mode = $variables['view_mode'];

  // Entity variables
  $variables['attributes']['class'][] = HTML::cleanCssIdentifier('entity-' . $view_mode);
  $variables['attributes']['class'][] = HTML::cleanCssIdentifier('entity-' . $view_mode . '--' . $term->bundle());
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bellcom_preprocess_node(&$variables) {
  $node = $variables['node'];
  $view_mode = $variables['view_mode'];

  // Entity variables
  $variables['attributes']['class'][] = HTML::cleanCssIdentifier('entity-' . $view_mode);
  $variables['attributes']['class'][] = HTML::cleanCssIdentifier('entity-' . $view_mode . '--' . $node->getType());
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bellcom_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];
  $view_mode = $variables['view_mode'];

  // Entity variables
  $variables['attributes']['class'][] = HTML::cleanCssIdentifier('entity-' . $view_mode);
  $variables['attributes']['class'][] = HTML::cleanCssIdentifier('entity-' . $view_mode . '--' . $paragraph->getType());
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bellcom_preprocess_block(array &$variables) {
  $variables['content']['#attributes']['block'] = $variables['elements']['#id'];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function bellcom_theme_suggestions_menu_alter(array &$suggestions, array $variables) {
  if (!empty($variables['attributes']['block'])) {
    $block = Drupal\block\Entity\Block::load($variables['attributes']['block']);
    $suggestions[] = 'menu__' . $block->getRegion();
  }
}


/**
 * Implements hook_theme_suggestions_hook
 */
function bellcom_theme_suggestions_user_alter(array &$suggestions, array $variables) {
  $suggestions[] = $variables['theme_hook_original'] . '__' . str_replace('-', '_', $variables['elements']['#view_mode']);
  return $suggestions;
}

/**
 * Implements template_preprocess_user
 * @param $variables
 */
function bellcom_preprocess_user(&$variables) {
  $variables['attributes']['class'][] = 'user';
  $variables['attributes']['class'][] = 'user--' . str_replace('-', '_', $variables['elements']['#view_mode']);
}
