<?php

/**
 * @file
 * Contains bc_settings.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bc_settings_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bc_settings module.
    case 'help.page.bc_settings':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Site settings module') . '</p>';
      return $output;

    default:
  }
}
