<?php

use Drupal\user\Entity\User;
use Drupal\bc_2movepeople_dashboard\Misc\Utils;
use Drupal\web_push_notification\Entity\SubscriptionInterface;
use Drupal\Core\Field\EntityReferenceFieldItemListInterface;
use Drupal\user\UserInterface;

/**
 * @file
 * Examples showing how to use some of the new JavaScript features in Drupal 8.
 */

define('BC_2MOVEPEOPLE_DASHBOARD_BUTTONS', serialize([
  'Progression' => [
    'feedback' => t('Feedback'),
    'show_category' => t('Show category'),
    'create_categories' => t('Create categories'),
    'rate_category' => t('Rates'),
    'save_to_template' => t('Save to template'),
  ],
  'Milestone' => [
    'overall_evaluation' => t('Overall evaluation'),
    'show_target_milestones' => t('Show Target Milestones'),
  ],
  'Navigation' => [
    'supervisor_create_user' => t('Add new employee (supervisor)'),
    'manager_create_user' => t('Add new user (manager)'),
    'create_user' => t('Add new user (others)'),
    'feedback' => t('Dialogue rating'),
    'self_rate' => t('Rates'),
  ],
  'Meetings' => [
    'meetings' => t('Meetings'),
  ],
]));

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\bc_2movepeople_dashboard\Misc\TaskReminderUtils;
use Drupal\node\Entity\Node;
use Drupal\bc_2movepeople_dashboard\Controller\MovepeopleDashboardController;
use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Link;

/**
 * Implements hook_theme().
 */
function bc_2movepeople_dashboard_theme() {
  $moduleHandler = \Drupal::service('module_handler');

  return [
    'bc_2movepeople_dashboard_accordion' => [
      'template' => 'accordion',
      'variables' => ['title' => NULL],
    ],
    'bc_2movepeople_dashboard' => [
      'template' => 'bc-2movepeople-dashboard',
      'variables' => [
        'title' => NULL,
        'user' => NULL,
        'subtitle' => NULL,
        'limit' => NULL,
        'progression_targets' => [],
      ],
    ],
    'bc_2movepeople_milestone_dashboard' => [
      'template' => 'bc-2movepeople-milestone-dashboard',
      'variables' => [
        'title' => NULL,
        'user' => NULL,
        'subtitle' => NULL,
        'milestone_targets' => [],
      ],
    ],
    'bc_2movepeople_dashboard_user_overview' => [
      'template' => 'bc-2movepeople-dashboard-user-overview',
      'variables' => [
        'title' => NULL,
        'user' => NULL,
        'table_progression' => NULL,
        'table_milestone' => NULL,
      ],
    ],
    'bc_2movepeople_dashboard_progression_total_table' => [
      'template' => 'bc-2movepeople-dashboard-progression-total-table',
      'variables' => [
        'type' => 'progression',
        'table_header' => [],
        'table_data' => [],
      ],
    ],
    'bc_2movepeople_dashboard_user_tasks_overview' => [
      'template' => 'bc-2movepeople-user-tasks',
      'variables' => [
        'title' => NULL,
        'tasks' => NULL,
        'user'  => NULL,
      ],
    ],
    'bc_2movepeople_milestone_evaluations' => [
      'template' => 'bc-2movepeople-milestone-evaluations',
      'variables' => [
        'message' => NULL,
        'title' => NULL,
        'user'  => NULL,
        'name' => NULL,
        'social_security_number' => NULL,
        'milestones_data' => [],
        'sbsys_enabled' => $moduleHandler->moduleExists('sbsys_integration'),
      ],
    ],
    'bc_2movepeople_milestone_evaluations_pdf' => [
      'template' => 'bc-2movepeople-milestone-evaluations-pdf',
      'variables' => [
        'header' => NULL,
        'user'  => NULL,
        'name' => NULL,
        'social_security_number' => NULL,
        'milestones_data' => [],
      ],
    ],
    'bc_2movepeople_manager_tasks_overview' => [
      'template' => 'bc-2movepeople-manager-tasks',
      'variables' => [
        'tasks' => NULL,
        'user'  => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_alter().
 */
function bc_2movepeople_dashboard_theme_suggestions_alter(array &$suggestions, array $variables) {

  if (isset($variables['element']) && isset($variables['element']['#type']) && $variables['element']['#type'] == 'form') {
    $original_theme_hook = $variables['theme_hook_original'];

    $suggestions[] = $original_theme_hook . '__' . str_replace('-', '_', $variables['element']['#id']);
  }
  return $suggestions;
}

/**
 * Implements hook_user_login().
 */
function bc_2movepeople_dashboard_user_login($account) {
  if (\Drupal::routeMatch()->getRouteName() == 'user.reset.login') {
    return;
  }

  $path = '/';
  $user_roles = $account->getRoles();
  if (in_array("2mp_user", $user_roles)) {
    $path = Url::fromRoute('bc_2movepeople_dashboard.user.tasks', ['user' => $account->id()])->toString();
  }
  $response = new RedirectResponse($path);
  $response->send();
}

/**
 * Implements hook_cron().
 */
function bc_2movepeople_dashboard_cron() {
  TaskReminderUtils::bulkReminder();
}

/**
 * Implements hook node_delete().
 */
function bc_2movepeople_dashboard_node_delete($node) {
  $node_type = $node->type->entity->label();

  if ($node_type == 'Progression target') {
    // Delete goals and subgoals.
    $deleted_goals_count = 0;
    $goals = $node->field_goal_ids->referencedEntities();
    if (is_array($goals)) {
      foreach ($goals as $goal) {
        $subgoals = $goal->field_subgoal->referencedEntities();
        if (is_array($subgoals)) {
          foreach ($subgoals as $subgoal) {
            $subgoal->delete();
            $deleted_goals_count++;
          }
        }
        $goal->delete();
        $deleted_goals_count++;
      }
    }
    // Delete rates values.
    $rates_values = \Drupal::database()->delete('bc_2movepeople_rate_progression')
      ->condition('progression_target_id', $node->id())
      ->execute();

    if ('target_milestone' == $node->get('field_progression_type')->getValue()[0]['value']) {
      drupal_set_message(t('Milestone @category_name is deleted. It had @tasks tasks', [
        '@category_name' => $node->getTitle(),
        '@tasks' => $deleted_goals_count,
      ]), 'status');
    }
    else {
      drupal_set_message(t('Category @category_name is deleted. It had @goals goals and @rates rates values', [
        '@category_name' => $node->getTitle(),
        '@goals' => $deleted_goals_count,
        '@rates' => $rates_values,
      ]), 'status');
    }
  }
}

/**
 * Implements hook_mail().
 */
function bc_2movepeople_dashboard_mail($key, &$message, $params) {
  switch ($key) {
    case 'sbsys':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      $message['params']['attachments'] = $params['attachments'];

      if (!isset($params['from'])) {
        $params['from'] = \Drupal::config('system.site')->get('mail');
      }

      break;

    default:
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      $message['headers'] = $params['headers'];
      break;
  }
}

/**
 * Implements hook entity_update().
 */
function bc_2movepeople_dashboard_entity_update(EntityInterface $entity) {
  switch ($entity->bundle()) {
    case 'goal':
      // Send notification only when node has been changed.
      $manager_id = $entity->field_responsible_manager->target_id;
      $original_manager_id = $entity->original->field_responsible_manager->target_id;
      // Consider '0' as empty reference.
      if ($original_manager_id == '0') {
        $original_manager_id = '';
      }

      if ($original_manager_id == $manager_id || (empty($original_manager_id) && empty($manager_id))) {
        return;
      }
      \Drupal::service('2movepeople_dashboard.mailer')->sendTaskNotification($entity, $manager_id);
      break;

    case 'user':
      $newUsers = $entity->get('field_connected_users')->referencedEntities();
      $oldUsers = $entity->original->get('field_connected_users')->referencedEntities();
      $users = array_merge($newUsers, $oldUsers);

      // Keeping only unique users.
      $updatedUsers = [];
      foreach ($users as $user) {
        $updatedUsers[$user->id()] = $user;
      }

      // Forcing users to be updated.
      foreach ($updatedUsers as $user) {
        // Adding original reference to avoid erorr during
        // search_api_entity_update call.
        $user->original = $user;
        search_api_entity_update($user);
      }

      break;
  }
}

/**
 * Implements hook_system_breadcrumb_alter().
 */
function bc_2movepeople_dashboard_system_breadcrumb_alter(&$breadcrumb, $route_match, array $context) {
  // Renaming link named 'Home' to 'Dashboard'.
  foreach ($breadcrumb->getLinks() as $exisiting_link) {
    if ($exisiting_link->getUrl()->getRouteName() == '<front>') {
      $exisiting_link->setText(t('Dashboard'));
    }
  }

  // User progressions - removing breadcrumb duplicate.
  if ($route_match->getRouteName() == 'bc_2movepeople_dashboard.user.progressions') {
    if ($route_match->getParameter('limit') != NULL) {
      _bc_2movepeople_dashboard_remove_breadcrubm_duplicate($breadcrumb, $route_match->getRouteName());
    }
  }

  // User progressions, User milestones.
  if ($route_match->getRouteName() == 'bc_2movepeople_dashboard.user.progressions'
    || $route_match->getRouteName() == 'bc_2movepeople_dashboard.user.milestones'
  ) {

    if ($route_match->getParameter('limit') != NULL) {
      _bc_2movepeople_dashboard_remove_breadcrubm_duplicate($breadcrumb, $route_match->getRouteName());
    }

    $user = $route_match->getParameter('user');
    $breadcrumb->addLink(Link::createFromRoute(t('User overview'), 'bc_2movepeople_dashboard.user.overview', ['user' => $user->id()]));
  }

  // Progression edit.
  if ($route_match->getRouteName() == 'bc_2movepeople_dashboard.progressions.edit') {
    if ($route_match->getParameter('limit') != NULL) {
      _bc_2movepeople_dashboard_remove_breadcrubm_duplicate($breadcrumb, $route_match->getRouteName());
    }

    $progression = $route_match->getParameter('node');
    $user_id = $progression->field_progression_user->target_id;

    $limit = $route_match->getParameter('limit');

    $breadcrumb->addLink(Link::createFromRoute(t('User overview'), 'bc_2movepeople_dashboard.user.overview', ['user' => $user_id]));
    $breadcrumb->addLink(Link::createFromRoute(t('User progressions'), 'bc_2movepeople_dashboard.user.progressions', [
      'user' => $user_id,
      'limit' => $limit,
    ]));
  }

  // Milestone edit.
  if ($route_match->getRouteName() == 'bc_2movepeople_dashboard.milestone.edit') {
    $progression = $route_match->getParameter('node');
    $user_id = $progression->field_progression_user->target_id;

    $limit = $route_match->getParameter('limit');

    $breadcrumb->addLink(Link::createFromRoute(t('User overview'), 'bc_2movepeople_dashboard.user.overview', ['user' => $user_id]));
    $breadcrumb->addLink(Link::createFromRoute(t('User milestones'), 'bc_2movepeople_dashboard.user.milestones', [
      'user' => $user_id,
      'limit' => $limit,
    ]));
  }
}

/**
 * Removed the duplicate from the breadcrumbs, if one is found.
 *
 * The duplicate comes automatically when the route contains default parameters as NULL.
 *
 * @param object $breadcrumb
 *   Breadcrumbs object.
 * @param string $route_name
 *   Route.
 */
function _bc_2movepeople_dashboard_remove_breadcrubm_duplicate(&$breadcrumb, $route_name) {
  $active_links = $breadcrumb->getLinks();
  foreach ($breadcrumb->getLinks() as $key => $link) {
    if ($link->getUrl()->getRouteName() == $route_name) {
      unset($active_links[$key]);
    }
  }
  if (count($active_links) != count($breadcrumb->getLinks())) {
    $breadcrumb = new Breadcrumb();
    $breadcrumb->setLinks($active_links);
  }
}

/**
 * Get buttons function.
 */
function _bc_2movepeople_dashboard_buttons() {
  return unserialize(BC_2MOVEPEOPLE_DASHBOARD_BUTTONS);
}

/**
 * Get button data by key.
 */
function _bc_2movepeople_dashboard_button($key) {
  $button = [
    'name' => NULL,
    'title' => NULL,
  ];
  $keys = explode('.', $key);
  $buttons = unserialize(BC_2MOVEPEOPLE_DASHBOARD_BUTTONS);
  $config = \Drupal::config('bc_2movepeople_dashboard.admin_buttons_title');

  if (!empty($keys[1]) && !empty($buttons[$keys[0]][$keys[1]])) {
    $button['name'] = $buttons[$keys[0]][$keys[1]];
    $button['title'] = $config->get($keys[0] . '.' . $keys[1]);
  }

  return $button;
}

/**
 * Implements hook_user_format_name_alter().
 *
 * If user has both first and last names, they are used as the user display
 * name.
 */
function bc_2movepeople_dashboard_user_format_name_alter(&$name, $account) {
  if ($account instanceof UserInterface == FALSE) {
    $user = User::load($account->id());
  }
  else {
    $user = $account;
  }

  $firstName = '';
  $lastName = '';

  // Getting first name.
  if ($user->field_user_firstname && !$user->field_user_firstname->isEmpty()) {
    if ($field_firstname = $user->get('field_user_firstname')->getValue()) {
      $firstName = $field_firstname[0]['value'];
    }
  }
  // Getting last name.
  if ($user->get('field_user_surname') && !$user->field_user_surname->isEmpty()) {
    if ($field_lastname = $user->get('field_user_surname')->getValue()) {
      $lastName = $field_lastname[0]['value'];
    }
  }

  // Only making swap if both first and last names are present.
  if ($firstName && $lastName) {
    $name = $firstName . ' ' . $lastName;
  }
}

/**
 * Implements template_preprocess_user().
 *
 * Adds rating to user display to users of role 2mp_user.
 */
function bc_2movepeople_dashboard_preprocess_user(&$variables) {
  $user = $variables['user'];

  // Only for 2mp_user role.
  if (in_array('2mp_user', $user->getRoles())) {
    $entity_progression_ids = MovepeopleDashboardController::getProgressionTargets($user->id(), 'progressions');
    $progression_table = MovepeopleDashboardController::getProgressionsTable($entity_progression_ids);

    $minRate = 0;

    foreach ($progression_table['data'] as $progressionRates) {
      if ($rate = end($progressionRates)) {
        if (!$minRate || $minRate > $rate) {
          $minRate = $rate;
        }
      }
    }

    $config = \Drupal::config('bc_2movepeople_dashboard.AdminSettings');
    $faq_node = NULL;
    if (!empty($config->get('faq_node_nid'))) {
      $faq_node = \Drupal::entityTypeManager()->getStorage('node')
        ->load($config->get('faq_node_nid'));
    }

    $variables['last_min_rate'] = $minRate;
    $variables['last_min_rate_text'] = ($faq_node) ? Link::fromTextAndUrl(' ' . $minRate, $faq_node->toUrl())
      ->toString() : $minRate;
  }

  $variables['destination'] = \Drupal::service('path.current')->getPath();
  $variables['has_connected_users'] = TRUE;
  if ($user->field_connected_users->isEmpty()) {
    $variables['has_connected_users'] = FALSE;
  }
}

/**
 * Implements template_preprocess_node().
 */
function bc_2movepeople_dashboard_preprocess_node(&$variables) {
  $node = $variables['node'];
  $view_mode = $variables['view_mode'];

  if ($node->getType() == 'goal' && $view_mode == 'teaser') {
    // Find progression target of a goal.
    $query = \Drupal::entityQuery('node');
    $query->condition('status', 1);
    $query->condition('type', 'progression_target');
    $query->condition('field_goal_ids', $node->id(), 'IN');
    $entity_ids = $query->execute();
    if (!empty($entity_ids)) {
      $progression_target_id = reset($entity_ids);
      $progression_target = Node::load($progression_target_id);

      // Adding progression user.
      $variables['progression_user'] = $progression_target->field_progression_user->target_id;
    }
  }

}

/**
 * Implements hook_views_data().
 */
function bc_2movepeople_dashboard_views_data() {
  $data['views']['table']['group'] = t('Global');
  $data['views']['table']['join'] = [
    // #global is a special flag which allows a table to appear all the time.
    '#global' => [],
  ];
  $data['views']['bc_2movepeople_dashboard_create_button'] = [
    'title' => t('Create user button'),
    'help' => t('Add button, to create user depends on role.'),
    'area' => [
      'id' => 'bc_2movepeople_dashboard_create_button',
    ],
  ];

  return $data;
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function bc_2movepeople_dashboard_wpn_subscription_insert(EntityInterface $entity) {
  if ($entity instanceof SubscriptionInterface && !\Drupal::currentUser()->isAnonymous()) {
    $user = User::load(\Drupal::currentUser());
    if ($user->hasField('field_wpn')
      && $user->get('field_wpn') instanceof EntityReferenceFieldItemListInterface) {
      $user->get('field_wpn')->appendItem($entity);
      $user->save();
    }
  }
}
