<?php

/**
 * @file
 * Examples showing how to use some of the new JavaScript features in Drupal 8.
 */

use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\bc_2movepeople_dashboard\Misc\TaskReminderUtils;
use Drupal\node\Entity\Node;
use Drupal\bc_2movepeople_dashboard\Controller\MovepeopleDashboardController;
use Drupal\Core\Breadcrumb\Breadcrumb;

/**
 * @defgroup bc_2movepeople_dashboard.module: JavaScript
 * @ingroup 2movepeople
 * @{
 *
 */

/**
 * Implements hook_theme().
 */
function bc_2movepeople_dashboard_theme() {
  return array(
    'bc_2movepeople_dashboard_accordion' => array(
      'template' => 'accordion',
      'variables' => array('title' => NULL),
    ),
    'bc_2movepeople_dashboard' => array(
      'template' => 'bc-2movepeople-dashboard',
      'variables' => array('title' => NULL,
        'user' => NULL,
        'subtitle' => NULL,
        'limit' => NULL,
        'progression_targets' => array()),
    ),
    'bc_2movepeople_milestone_dashboard' => array(
      'template' => 'bc-2movepeople-milestone-dashboard',
      'variables' => array('title' => NULL,
        'user' => NULL,
        'subtitle' => NULL,
        'milestone_targets' => array()),
    ),
    'bc_2movepeople_dashboard_user_overview' => array(
      'template' => 'bc-2movepeople-dashboard-user-overview',
      'variables' => array('title' => NULL,
      'user' => NULL,
      'table_progression' => NULL, 'table_milestone' => NULL),
    ),
    'bc_2movepeople_dashboard_progression_total_table' => array(
      'template' => 'bc-2movepeople-dashboard-progression-total-table',
      'variables' => array(
      'type' => 'progression',
      'table_header' => array(),
      'table_data' => array()),
    ),
    'bc_2movepeople_dashboard_user_tasks_overview' => array(
      'template' => 'bc-2movepeople-user-tasks',
      'variables' => array(
          'title' => NULL,
          'tasks' => NULL,
          'user'  => NULL
      ),
    ),
    'bc_2movepeople_milestone_evaluations' => array(
      'template' => 'bc-2movepeople-milestone-evaluations',
      'variables' => array(
        'title' => NULL,
        'user'  => NULL,
        'milestones_data' => array(),
        ),
    ),
    'bc_2movepeople_milestone_evaluations_pdf' => array(
      'template' => 'bc-2movepeople-milestone-evaluations-pdf',
      'variables' => array(
        'user'  => NULL,
        'milestones_data' => array(),
        ),
    ),
  );
}

/**
 * Implements hook_theme_suggestions_alter
 */
function bc_2movepeople_dashboard_theme_suggestions_alter(array &$suggestions, array $variables) {

    if (isset($variables['element']) && isset($variables['element']['#type']) && $variables['element']['#type'] == 'form') {
        $original_theme_hook = $variables['theme_hook_original'];

        $suggestions[] = $original_theme_hook . '__' . str_replace('-', '_', $variables['element']['#id']);
    }
    return $suggestions;
}

/**
 * Implements hook_user_login().
 */
function bc_2movepeople_dashboard_user_login($account) {
    $path = '/';
    $user_roles = $account->getRoles();
    if (in_array("2mp_user", $user_roles)) {
      $path = Url::fromRoute('bc_2movepeople_dashboard.user.tasks', ['user' => $account->id()])->toString();
    }  
    $response = new RedirectResponse($path);
    $response->send(); 
}

/**
 * Implements hook_cron().
 */
function bc_2movepeople_dashboard_cron() {
  TaskReminderUtils::bulkReminder();
}

/**
 * Implements hook node_delete()
 */
function bc_2movepeople_dashboard_node_delete($node) {
  $node_type = $node->type->entity->label();

  if($node_type == 'Progression target'){
    //Delete goals and subgoals
    $deleted_goals_count = 0;
    $goals = $node->field_goal_ids->referencedEntities();  
      if (is_array($goals)) {
        foreach ($goals as $goal) {
          if (is_array($subgoals = $goal->field_subgoal->referencedEntities())) {
            foreach ($subgoals as $subgoal) {
              $subgoal->delete();
              $deleted_goals_count++;
            }
          }
          $goal->delete();
          $deleted_goals_count++;
        }
      }
    //Delete rates values
    $rates_values = \Drupal::database()->delete('bc_2movepeople_rate_progression')
    ->condition('progression_target_id', $node->id())
    ->execute();
  
    if('target_milestone' == $node->get('field_progression_type')->getValue()[0]['value']){
      drupal_set_message(t('Milestone @category_name is deleted. It had @tasks tasks', 
      array('@category_name' => $node->getTitle(), '@tasks' => $deleted_goals_count)), 'status');
    }else{
      drupal_set_message(t('Category @category_name is deleted. It had @goals goals and @rates rates values', 
      array('@category_name' => $node->getTitle(), '@goals' => $deleted_goals_count, '@rates' => $rates_values)), 'status');
    } 
  }
}

/**
 * Implements hook entity_presave()
 */
function bc_2movepeople_dashboard_entity_presave(\Drupal\Core\Entity\EntityInterface $entity) {
  switch ($entity->bundle()) {
    // Here we send notifications only if 'goal' content type has assigned to responsible manager
    case 'goal':
      $manager_id = $entity->field_responsible_manager->target_id;
      $original_manager_id = $entity->original->field_responsible_manager->target_id;

      if ((empty($original_manager_id) || ($original_manager_id <> $manager_id)) && !empty($manager_id)) {
        // Get milestone of the goal
        $bundle = 'progression_target';
        $query = \Drupal::entityQuery('node');
        $query->condition('status', 1);
        $query->condition('type', $bundle);
        $query->condition('field_goal_ids', $entity->id(), 'CONTAINS');
        $query->range(0, 1);
        $milestone_id = $query->execute();
        $milestone = Node::load(array_pop($milestone_id));
        // Get milestone user
        $milestone_user = $milestone->get('field_progression_user')->referencedEntities()[0];
        
        $manager = $entity->get('field_responsible_manager')->referencedEntities()[0];
        $config = \Drupal::config('bc_2movepeople_dashboard.AdminSettings');
        $subject = $config->get('responsible_manager_email_subject');
        $body = $config->get('responsible_manager_email_body');
        $body = str_replace("@manager", $manager->getDisplayName(), $body);
        $body = str_replace("@user", $milestone_user->getDisplayName(), $body);
        $body = str_replace("@task_title", $entity->get('title')->value, $body);

        MovepeopleDashboardController::sendMail([
          'to' => $manager->get('mail')->value,
          'from' => \Drupal::config('system.site')->get('mail'),
          'subject' => $subject,
          'body' => $body,
          'sender' => t('System notify')
        ]);
        break;
      }
  }
}

/**
 * Implements hook_system_breadcrumb_alter().
 *
 * @param $breadcrumb
 * @param $route_match
 * @param array $context
 */
function bc_2movepeople_dashboard_system_breadcrumb_alter(&$breadcrumb, $route_match, array $context) {
  // Renaming link named 'Home' to 'Dashboard'.
  foreach ($breadcrumb->getLinks() as $exisiting_link) {
    if ($exisiting_link->getUrl()->getRouteName() == '<front>') {
      $exisiting_link->setText(t('Dashboard'));
    }
  }

  // User progressions - removing breadcrumb duplicate.
  if ($route_match->getRouteName() == 'bc_2movepeople_dashboard.user.progressions') {
    if ($route_match->getParameter('limit') != NULL) {
      _bc_2movepeople_dashboard_remove_breadcrubm_duplicate($breadcrumb, $route_match->getRouteName());
    }
  }

  // User progressions, User milestones
  if ($route_match->getRouteName() == 'bc_2movepeople_dashboard.user.progressions'
    || $route_match->getRouteName() == 'bc_2movepeople_dashboard.user.milestones'
  ) {

    if ($route_match->getParameter('limit') != NULL) {
      _bc_2movepeople_dashboard_remove_breadcrubm_duplicate($breadcrumb, $route_match->getRouteName());
    }

    $user = $route_match->getParameter('user');
    $breadcrumb->addLink(\Drupal\Core\Link::createFromRoute(t('User overview'), 'bc_2movepeople_dashboard.user.overview', ['user' => $user->id()]));
  }

  // Progression edit.
  if ($route_match->getRouteName() == 'bc_2movepeople_dashboard.progressions.edit') {
    if ($route_match->getParameter('limit') != NULL) {
      _bc_2movepeople_dashboard_remove_breadcrubm_duplicate($breadcrumb, $route_match->getRouteName());
    }

    $progression = $route_match->getParameter('node');
    $user_id = $progression->field_progression_user->target_id;

    $limit = $route_match->getParameter('limit');

    $breadcrumb->addLink(\Drupal\Core\Link::createFromRoute(t('User overview'), 'bc_2movepeople_dashboard.user.overview', ['user' => $user_id]));
    $breadcrumb->addLink(\Drupal\Core\Link::createFromRoute(t('User progressions'), 'bc_2movepeople_dashboard.user.progressions', [
      'user' => $user_id,
      'limit' => $limit
    ]));
  }

  // Milestone edit.
  if ($route_match->getRouteName() == 'bc_2movepeople_dashboard.milestone.edit') {
    $progression = $route_match->getParameter('node');
    $user_id = $progression->field_progression_user->target_id;

    $limit = $route_match->getParameter('limit');

    $breadcrumb->addLink(\Drupal\Core\Link::createFromRoute(t('User overview'), 'bc_2movepeople_dashboard.user.overview', ['user' => $user_id]));
    $breadcrumb->addLink(\Drupal\Core\Link::createFromRoute(t('User milestones'), 'bc_2movepeople_dashboard.user.milestones', [
      'user' => $user_id,
      'limit' => $limit
    ]));
  }
}

/**
 * Removed the duplicate from the breadcrumbs, if one is found.
 *
 * The duplicate comes automatically when the route contains default parameters as NULL.
 *
 * @param $breadcrumb
 * @param $route_name
 */
function _bc_2movepeople_dashboard_remove_breadcrubm_duplicate(&$breadcrumb, $route_name) {
  $active_links = $breadcrumb->getLinks();
  foreach ($breadcrumb->getLinks() as $key => $link) {
    if ($link->getUrl()->getRouteName() == $route_name) {
      unset($active_links[$key]);
    }
  }
  if (count($active_links) != count($breadcrumb->getLinks())) {
    $breadcrumb = new Breadcrumb();
    $breadcrumb->setLinks($active_links);
  }
}
