<?php

use Drupal\node\Entity\Node;

function bc_2movepeople_dashboard_schema() {
  $schema['bc_2movepeople_dashboard_task_reminder'] = array(
    'description' => 'This table stores reminded tasks',
    'fields' => array(
      'nid' => array(
        'description' => 'Goal id',
        'type' => 'int',
        'not null' => TRUE,
      ),
      'reminded_count' => array(
        'description' => 'Reminded count (1..n)',
        'type' => 'int',
        'not null' => TRUE,
      ),
      'email' => array(
        'description' => 'User is email of who got last remind',
        'type' => 'varchar',
        'length' => 64,
        'default' => '',
        'not null' => TRUE,
      ),
      'reminded_date' => array(
        'description' => 'Timestamp of last remind',
        'type' => 'int',
        'unsigned' => TRUE,
      ),
    ),
    'primary key' => array('nid'),
  );
  return $schema;
}

/**
 * Add default value for field 'field_task_show_complete_button'.
 */
function bc_2movepeople_dashboard_update_8001() {
  $node_goal_definition = \Drupal::service('entity_field.manager')->getFieldDefinitions('node', 'goal');
  if (empty($node_goal_definition['field_task_show_complete_button'])
    || empty($node_goal_definition['field_task_links'])) {
    return;
  }

  $query = \Drupal::entityQuery('node');
  $query->condition('status', 1);
  $query->condition('type', 'goal');
  $query->notExists('field_task_links');
  $query->notExists('field_task_show_complete_button');
  $nids = $query->execute();
  /** @var \Drupal\node\NodeInterface $node */
  foreach (Node::loadMultiple($nids) as $node) {
    $node->set('field_task_show_complete_button', ['value' => 1])->save();
  }
}

/**
 * Install web_push_notification module.
 */
function bc_2movepeople_dashboard_update_8801() {
  \Drupal::service('module_installer')->install(['web_push_notification']);
}
