<?php

use Drupal\node\Entity\Node;
use Drupal\Core\Entity\ContentEntityType;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\bc_2movepeople_dashboard\Entity\Evaluation;
use Drupal\bc_2movepeople\Form\TextSettings;

function bc_2movepeople_dashboard_schema() {
  $schema['bc_2movepeople_dashboard_task_reminder'] = array(
    'description' => 'This table stores reminded tasks',
    'fields' => array(
      'nid' => array(
        'description' => 'Goal id',
        'type' => 'int',
        'not null' => TRUE,
      ),
      'reminded_count' => array(
        'description' => 'Reminded count (1..n)',
        'type' => 'int',
        'not null' => TRUE,
      ),
      'email' => array(
        'description' => 'User is email of who got last remind',
        'type' => 'varchar',
        'length' => 64,
        'default' => '',
        'not null' => TRUE,
      ),
      'reminded_date' => array(
        'description' => 'Timestamp of last remind',
        'type' => 'int',
        'unsigned' => TRUE,
      ),
    ),
    'primary key' => array('nid'),
  );
  return $schema;
}

/**
 * Add default value for field 'field_task_show_complete_button'.
 */
function bc_2movepeople_dashboard_update_8001() {
  $node_goal_definition = \Drupal::service('entity_field.manager')->getFieldDefinitions('node', 'goal');
  if (empty($node_goal_definition['field_task_show_complete_button'])
    || empty($node_goal_definition['field_task_links'])) {
    return;
  }

  $query = \Drupal::entityQuery('node');
  $query->condition('status', 1);
  $query->condition('type', 'goal');
  $query->notExists('field_task_links');
  $query->notExists('field_task_show_complete_button');
  $nids = $query->execute();
  /** @var \Drupal\node\NodeInterface $node */
  foreach (Node::loadMultiple($nids) as $node) {
    $node->set('field_task_show_complete_button', ['value' => 1])->save();
  }
}

/**
 * Add default text and titles.
 */
function bc_2movepeople_dashboard_update_8902(&$sandbox) {
  $config = \Drupal::service('config.factory')->getEditable(TextSettings::$config_name);
  $config->set('bc_2movepeople_dashboard.manager_tasks', t('Manager tasks'));
  $config->save();
}

/**
 * Adds new content entity type for Evaluation.
 */
function bc_2movepeople_dashboard_update_8903() {
  $definition_update_manager = \Drupal::entityDefinitionUpdateManager();

  $definition_update_manager->installEntityType(new ContentEntityType([
    'id' => 'evaluation',
    'label' => new TranslatableMarkup('Evaluation'),
    'handlers' => [
      'view_builder' => 'Drupal\Core\Entity\EntityViewBuilder',
      'list_builder' => 'Drupal\bc_2movepeople_dashboard\EvaluationListBuilder',
      'views_data' => 'Drupal\bc_2movepeople_dashboard\Entity\EvaluationViewsData',
    ],
    'base_table' => 'evaluation',
    'translatable' => FALSE,
    'admin_permission' => 'administer evaluation entities',
    'entity_keys' => [
      'id' => 'id',
    ],
  ]));

  $entity_type = $definition_update_manager->getEntityType('evaluation');
  $fields = Evaluation::baseFieldDefinitions($entity_type);
  foreach ($fields as $field_name => $field_definition) {
    $definition_update_manager->installFieldStorageDefinition($field_name, 'evaluation', 'evaluation', $field_definition);
  }
}
