<?php

/**
 * @file
 * Functions to support theming in the site theme.
 */

use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;
use Drupal\bc_2movepeople_dashboard\Controller\MovepeopleDashboardController;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * This changes the button "Add new user / manager" according to the logged in user's role
 */

// Get the current user id
$uid = \Drupal::currentUser()->id();
// Get the user entity
$user = \Drupal\user\Entity\User::load($uid);
// Put the user entity through this function and put the output in a variable
$account_role = bc_2movepeople_dashboard2_user_login($user);
$add_new_user_button = 'user';

if($account_role === "2mp_supervisor"){
	$add_new_user_button = 'manager';
}

/**
 * This is moved from the bc_2movepeople_dashboard module in the bc_2movepeople_dashboard.module file.
 * The reason to why it's moved, was because it was easier to configure in the theme files (apparently)
 * opposed to in the module files. The below seems to work nonetheless, but this makes it important
 * the theme and modules are installed and activated at the same time. Unfortunately, this was the only
 * solution I could come up with.
 * @inuitviking on github.com
 */
 define('BC_2MOVEPEOPLE_DASHBOARD_BUTTONS', serialize([
   'Progression' => [
     'feedback' => t('FIT'),
     'show_category' => t('Show category'),
     'rate_category' => t('Rates'),
     'save_to_template' => t('Save to template'),
   ],
   'Milestone' => [
     'overall_evaluation' => t('Overall evaluation'),
     'show_target_milestones' => t('Show Target Milestones'),
   ],
   'Navigation' => [
     'create_user' => t("Add new $add_new_user_button"),
     'feedback' => t('Dialogue rating'),
     'self_rate' => t('Rates'),
   ],
 ]));

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function site_theme_suggestions_image_formatter_alter(array &$suggestions, array $variables) {
  $entity = $variables['item']->getEntity();
  $field_name = $variables['item']->getParent()->getName();
  $suggestions[] = 'image_formatter__' . $entity->getEntityTypeId() . '__' . $entity->bundle() . '__' . $field_name;
}

/**
 * Implements hook_preprocess_page() for page.html.twig.
 */
function site_preprocess_page(array &$variables) {
  $user_roles = \Drupal::currentUser()->getRoles();
  $current_url = Url::fromRoute('<current>')->toString();
  $front_uri = array(
    Url::fromRoute('<front>')->toString(),
    '/dashboard',
    '/system/403',
  );

  if (in_array("2mp_user", $user_roles)) {
    if (in_array($current_url, $front_uri)) {
      $path = Url::fromRoute('bc_2movepeople_dashboard.user.tasks', ['user' => \Drupal::currentUser()->id()])->toString();
      $response = new RedirectResponse($path);
      $response->send();
    }

    if (MovepeopleDashboardController::checkUserSessionReminder()) {
      MovepeopleDashboardController::setUserTasksReminder(\Drupal::currentUser()->id());
    }
  }
  $session = new Session();
  $state = $session->get('menu_toggle');
  $variables['menu_toggle_state'] = (integer) $state;
  $variables['menu_toggle'] = [
    '#theme' => 'bc_2movepeople_menu_toggle',
    '#state' => empty((integer) $state) ? '0' : $state,
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function site_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  $current_path = \Drupal::service('path.current')->getPath();
  $result = \Drupal::service('path.alias_manager')->getAliasByPath($current_path);

  $path_alias = trim($result, '/');
  $path_alias = str_replace('/', '-', $path_alias);

  $suggestions[] = 'page__' . $path_alias;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function site_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['name']['#attributes']['autofocus'])) {
    unset($form['name']['#attributes']['autofocus']);
  }
}

/**
 * Implements template_preprocess_user().
 */
function site_preprocess_user(&$variables) {
  $user = $variables['user'];
  $view_mode = $variables['elements']['#view_mode'];

  $variables['url'] = $user->toUrl();
  $variables['uid'] = $user->id();
}
