<?php

/**
 * @file
 * Functions to support theming in the site theme.
 */

use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;
use Drupal\bc_2movepeople_dashboard\Controller\MovepeopleDashboardController;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function site_theme_suggestions_image_formatter_alter(array &$suggestions, array $variables) {
  $entity = $variables['item']->getEntity();
  $field_name = $variables['item']->getParent()->getName();
  $suggestions[] = 'image_formatter__' . $entity->getEntityTypeId() . '__' . $entity->bundle() . '__' . $field_name;
}

/**
 * Implements hook_preprocess_page() for page.html.twig.
 */
function site_preprocess_page(array &$variables) {
  $user_roles = \Drupal::currentUser()->getRoles();
  $current_url = Url::fromRoute('<current>')->toString();
  $front_uri = array(
    Url::fromRoute('<front>')->toString(),
    '/dashboard',
    '/system/403',
  );

  if (in_array("2mp_user", $user_roles)) {
    if (in_array($current_url, $front_uri)) {
      $path = Url::fromRoute('bc_2movepeople_dashboard.user.tasks', ['user' => \Drupal::currentUser()->id()])->toString();
      $response = new RedirectResponse($path);
      $response->send();
    }

    if (MovepeopleDashboardController::checkUserSessionReminder()) {
      MovepeopleDashboardController::setUserTasksReminder(\Drupal::currentUser()->id());
    }
  }
  $session = new Session();
  $state = $session->get('menu_toggle');
  $variables['menu_toggle_state'] = (integer) $state;
  $variables['menu_toggle'] = [
    '#theme' => 'bc_2movepeople_menu_toggle',
    '#state' => empty((integer) $state) ? '0' : $state,
  ];

  $variables['relative_logo_url'] = file_url_transform_relative(file_create_url(theme_get_setting('logo.url')));
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function site_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  $current_path = \Drupal::service('path.current')->getPath();
  $result = \Drupal::service('path.alias_manager')->getAliasByPath($current_path);

  $path_alias = trim($result, '/');
  $path_alias = str_replace('/', '-', $path_alias);

  $suggestions[] = 'page__' . $path_alias;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function site_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['name']['#attributes']['autofocus'])) {
    unset($form['name']['#attributes']['autofocus']);
  }
}

/**
 * Implements template_preprocess_user().
 */
function site_preprocess_user(&$variables) {
  $user = $variables['user'];
  $view_mode = $variables['elements']['#view_mode'];

  $variables['url'] = $user->toUrl();
  $variables['uid'] = $user->id();
}
