<?php

/**
 * @file
 * Contains bc_webform.module.
 */

use \Drupal\bc_webform\BcWebformHandler;
use \Drupal\Core\Session\AccountInterface;
use \Drupal\Core\Access\AccessResult;
use \Drupal\webform\WebformInterface;
use \Drupal\webform\WebformSubmissionInterface;
use \Drupal\taxonomy\Entity\Term;
use \Drupal\Core\Form\FormStateInterface;
use \Drupal\webform\WebformSubmissionForm;
use \Drupal\bc_2movepeople\Form\ConfigForm;

define('BC_WEBFORM_ROLES', serialize([
  '2mp_user' => '2mp_user',
  ]));

define('BC_WEBFORM_CONFIG', 'bc_webform.settings');
define('BC_WEBFORM_DAYS_TO_COMPLETE_TASK', 7);

/**
 * Implements hook_menu_links_discovered_alter().
 */
function bc_webform_menu_links_discovered_alter(&$links) {
  if (bc_webform_is_enabled()) {
    $links['bc_webform.questionnaire'] = [
      'title' => t('Questionnaire'),
      'route_name' => 'bc_webform.collection',
      'menu_name' => 'settings-menu',
      'weight' => -7,
    ];
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function bc_webform_webform_submission_presave(WebformSubmissionInterface $webform_submission) {
  if (!bc_webform_has_anonymization($webform_submission->getWebform())
    || (
      $webform_submission->getOwner()->hasRole('anonymous')
      && in_array('anonymous', $webform_submission->getWebform()->getThirdPartySetting('bc_webform', 'roles'))
    )
  ) {
    return;
  }

  $bc_webform_handler = new BcWebformHandler($webform_submission->getWebform());
  $user_id = $webform_submission->getOwnerId();
  if (empty($user_id) && $token_user_id = $bc_webform_handler->getUserIdFromToken()) {
    $user_id = $token_user_id;
  }
  $bc_webform_handler->registerUserSubmission($user_id, $webform_submission->getToken());
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function bc_webform_webform_submission_insert(WebformSubmissionInterface $webform_submission) {
  $bc_webform_handler = new BcWebformHandler($webform_submission->getWebform());
  $bc_webform_handler->completeUserTask($webform_submission);
}
/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function bc_webform_webform_delete(WebformInterface $webform) {
  // Removing created webform submittions tasks.
  $bc_webform_handler = new BcWebformHandler($webform);
  $bc_webform_handler->cleanUp();
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function bc_webform_webform_access(WebformInterface $webform, $operation, AccountInterface $account) {
  $bc_webform_handler = new BcWebformHandler($webform);
  $user_id = $account->id();

  if (empty($user_id) && $token_user_id = $bc_webform_handler->getUserIdFromToken()) {
    $user_id = $token_user_id;
  }

  if ($user_id > 1 && !$bc_webform_handler->matchOrganization($user_id)) {
    return AccessResult::forbidden();
  }

  if (!empty($token_user_id) && $user_id === $token_user_id
    && in_array($operation, ['submission_page', 'submission_create'])) {
    return AccessResult::allowed();
  }

  return AccessResult::neutral();
}

/**
 * Implements hook_form_alter().
 */
function bc_webform_form_alter(array &$form, FormStateInterface $form_state) {
  if (($form_state->getFormObject() instanceof WebformSubmissionForm)
    && \Drupal::routeMatch()->getRouteName() == 'entity.webform.canonical') {
    bc_webform_webform_submission_custom_alter($form, $form_state);
  }
}

/**
 * Implements hook_webform_help_info_alter().
 */
function bc_webform_webform_help_info_alter(array &$help) {
  if (array_intersect(
    [
      '2mp_supervisor',
      '2mp_manager',
      '2mp_user',
    ],
    \Drupal::currentUser()->getRoles()
  )) {
    $help = [];
  }
}

/**
 * Implements custom form alter.
 */
function bc_webform_webform_submission_custom_alter(array &$form, FormStateInterface $form_state) {
  /** @var WebformSubmissionInterface $webform_submission */
  $webform_submission = $form_state->getFormObject()->getEntity();
  $roles = $webform_submission->getWebform()->getThirdPartySetting('bc_webform', 'roles') ?: [];
  if (!bc_webform_has_anonymization($webform_submission->getWebform())
    || (
      $webform_submission->getOwner()->hasRole('anonymous')
      && in_array('anonymous', $roles)
      )
  ) {
    return;
  }

  $bc_webform_handler = new BcWebformHandler($webform_submission->getWebform());
  $messenger = \Drupal::service('messenger');

  $user_id = $webform_submission->getOwnerId();
  if (empty($user_id) && $token_user_id = $bc_webform_handler->getUserIdFromToken()) {
    $user_id = $token_user_id;
  }

  if (!$bc_webform_handler->isAllowedSubmit($user_id)
    || !$bc_webform_handler->matchOrganization($user_id)
    ) {
    $messenger->addMessage(t("You don't have access to send submission for this form."), 'warning');
    $form['#disabled'] = TRUE;
    return;
  }

  if ($bc_webform_handler->userHasSubmittion($user_id)) {
    $messenger = \Drupal::service('messenger');
    $messenger->addMessage(t('You already sent submission for this form.'), 'warning');
    $form['#disabled'] = TRUE;
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function bc_webform_form_webform_results_clear_alter(array &$form, FormStateInterface $form_state) {
  $form['#submit'][] = 'bc_werform_results_clear_submit';
}

function bc_werform_results_clear_submit(array $form, FormStateInterface $form_state) {
  /** @var WebformInterface $webform */
  list($webform, $sourceEntity) = \Drupal::service('webform.request')->getWebformEntities();
  if (!bc_webform_has_anonymization($webform)) {
    return;
  }
  $bc_webform_handler = new BcWebformHandler($webform);
  $bc_webform_handler->resetSubmissions();
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * Altering general webform settings.
 */
function bc_webform_form_webform_form_alter(array &$form, FormStateInterface $form_state) {
  if (!in_array($form['#form_id'], ['webform_add_form', 'webform_settings_form'])) {
    return;
  }
  $bc_webform_settings = \Drupal::config(BC_WEBFORM_CONFIG);
  /** @var WebformInterface $webform */
  $webform = $form_state->getFormObject()->getEntity();
  $available_roles_ids = empty($bc_webform_settings->get('roles')) ? [] : $bc_webform_settings->get('roles');
  $available_roles = \Drupal::entityTypeManager()->getStorage('user_role')->loadMultiple($available_roles_ids);
  $form['bc_webform'] = [
    '#type' => 'details',
    '#title' => t('Additional webform settings'),
    '#weight' => 4,
    '#open' => TRUE,
    '#collapsible' => TRUE,
    '#tree' => TRUE,
  ];

  $options = [];
  foreach ($available_roles as $role) {
    $options[$role->id()] = $role->label();
  }

  $access = $webform->getAccessRules();
  $form['bc_webform']['roles'] = [
    '#type' => 'checkboxes',
    '#title' => t('Roles that have the ability to submit submissions'),
    '#options' => $options,
    '#default_value' => empty($webform->id()) ? $available_roles_ids : $access['create']['roles'],
  ];
  $form['bc_webform']['roles_info'] = [
    '#type' => 'markup',
    '#markup' => t('ATTENTION: For webforms with anonymous access it is not possible to track submission coverage.'),
  ];

  $user = $webform->getOwner();
  $values = $user->get('field_organisation')->getValue();
  $user_organization_tid = $webform->getThirdPartySetting('bc_webform', 'organisation_tid');
  $options = [];
  foreach ($values as $value) {
    $options[$value['target_id']] = Term::load($value['target_id'])->name->value;
  }
  $form['bc_webform']['organisation_tid'] = [
    '#type' => 'select',
    '#options' => $options,
    '#title' => t('Organisation'),
    '#default_value' => empty($user_organization_tid) ? NULL : $user_organization_tid,
  ];

  $days_to_complete_task = $webform->getThirdPartySetting('bc_webform', 'days_to_complete_task');
  if (empty($days_to_complete_task)) {
    $days_to_complete_task = empty($bc_webform_settings->get('days_to_complete_task')) ? BC_WEBFORM_DAYS_TO_COMPLETE_TASK : $bc_webform_settings->get('days_to_complete_task');
  }
  $form['bc_webform']['days_to_complete_task'] = [
    '#type' => 'number',
    '#title' => t('Amount of days to complete webform submit task'),
    '#default_value' => $days_to_complete_task,
  ];

  $anonymization = empty($webform->id()) ? TRUE : bc_webform_has_anonymization($webform);
  $form['bc_webform']['anonymization'] = [
    '#type' => 'checkbox',
    '#title' => t('Submission anonymization'),
    '#default_value' => isset($anonymization) ? $anonymization : TRUE,
  ];

  $form['actions']['submit']['#submit'][] = 'bc_webform_webform_form_submit';
}

/**
 * Custom form submission handler for 'webform_settings_form'.
 *
 * Saving general webform settings.
 */
function bc_webform_webform_form_submit(array $form, FormStateInterface $form_state) {
  /** @var WebformInterface $webform */
  $webform = $form_state->getFormObject()->getEntity();
  $settings = &$form_state->getValue('bc_webform');
  $access_rules = $webform->getAccessRules();
  $access_rules['create']['roles'] = $settings['roles'];
  $webform->setAccessRules($access_rules);
  $webform->setThirdPartySetting('bc_webform', 'organisation_tid', $settings['organisation_tid']);
  $webform->setThirdPartySetting('bc_webform', 'days_to_complete_task', $settings['days_to_complete_task']);

  if ($settings['anonymization'] && !bc_webform_has_anonymization($webform)) {
    /** @var \Drupal\webform\Plugin\WebformHandlerManagerInterface $handler_manager */
    $handler_manager = \Drupal::service('plugin.manager.webform.handler');

    // Create webform handler.
    $handler_configuration = [
      'id' => 'anonymous_submission',
      'label' => 'Anonymous submission',
      'handler_id' => 'anonymous_submission',
      'status' => 1,
      'weight' => 0,
      'settings' => [],
    ];
    $handler = $handler_manager->createInstance('anonymous_submission', $handler_configuration);

    // Must set original id so that the webform can be resaved.
    $webform->setOriginalId($webform->id());

    // Add webform handler which triggers Webform::save().
    $webform->addWebformHandler($handler);
  }
  if (empty($settings['anonymization']) && bc_webform_has_anonymization($webform)) {
    $webform->deleteWebformHandler($webform->getHandler('anonymous_submission'));
  }
  $webform->save();
}

/**
 * Checks if webform use AnonymousSubmission Handler.
 *
 * @param WebformInterface $webform
 *
 * @return bool
 */
function bc_webform_has_anonymization(WebformInterface $webform) {
  $handlers = $webform->getHandlers();
  if ($handlers->has('anonymous_submission')
    && $handlers->get('anonymous_submission')->getStatus()
  ) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Altering general 2movepeople settings.
 */
function bc_webform_form_bc_2movepeople_config_form_alter(array &$form, FormStateInterface $form_state) {
  $form['functionality']['bc_webform_enabled'] = [
    '#type' => 'checkbox',
    '#title' => t('Enable Questinaire menu item'),
    '#default_value' => bc_webform_is_enabled(),
  ];
  $form['#submit'][] = 'bc_webform_bc_2movepeople_config_form_submit';

  $config = \Drupal::config(BC_WEBFORM_CONFIG);
  $form['#submit'][] = 'bc_webform_2mp_dashboard_submit';

  // Complete email options.
  $form['bc_webform'] = array(
    '#type' => 'details',
    '#title' => t('Webforms settings'),
    '#tree' => TRUE,
    '#open' => bc_webform_is_enabled(),
  );

  $options = [];
  $available_roles = \Drupal::entityTypeManager()->getStorage('user_role')->loadMultiple();
  foreach ($available_roles as $role) {
    if (strpos($role->id(), '2mp') === FALSE && $role->id() != 'anonymous') {
      continue;
    }
    $options[$role->id()] = $role->label();
  }
  $form['bc_webform']['roles'] = [
    '#type' => 'checkboxes',
    '#title' => t('Roles that have the ability to submit submissions'),
    '#options' => $options,
    '#default_value' => empty($config->get('roles')) ? unserialize(BC_WEBFORM_ROLES) : $config->get('roles'),
  ];
  $form['bc_webform']['days_to_complete_task'] = [
    '#type' => 'number',
    '#title' => t('Amount of days to complete webform submit task'),
    '#default_value' => empty($config->get('days_to_complete_task')) ? BC_WEBFORM_DAYS_TO_COMPLETE_TASK : $config->get('days_to_complete_task'),
  ];
}

/**
 * Get function for bc_webform state.
 */
function bc_webform_is_enabled() {
  $config = \Drupal::service('config.factory')->get(ConfigForm::getConfigName());
  return empty($config->get('bc_webform_enabled')) ? FALSE : TRUE;
}

/**
 * Custom form submission handler for 'bc_webform_bc_2movepeople_config_form'.
 *
 * Saving general webform enable state.
 */
function bc_webform_bc_2movepeople_config_form_submit(array $form, FormStateInterface $form_state) {
  $config = \Drupal::service('config.factory')->getEditable(ConfigForm::getConfigName());
  $bc_webform_enabled = $form_state->getValue('bc_webform_enabled');
  $bc_webform_enabled_original = bc_webform_is_enabled();
  $config->set('bc_webform_enabled', $bc_webform_enabled);
  $config->save();

  // Rebuild menu to update menu items at bc_webform_menu_links_discovered_alter().
  if ($bc_webform_enabled != $bc_webform_enabled_original) {
    \Drupal::service('plugin.manager.menu.link')->rebuild();
  }
}

/**
 * Custom form submission handler for 'bc_2movepeople_dashboard_admin_settings_form'.
 *
 * Saving general webform settings.
 */
function bc_webform_2mp_dashboard_submit(array $form, FormStateInterface $form_state) {
  $config = \Drupal::service('config.factory')->getEditable(BC_WEBFORM_CONFIG);
  $bc_webform = $form_state->getValue('bc_webform');
  $config
    ->set('roles', $bc_webform['roles'])
    ->set('days_to_complete_task', $bc_webform['days_to_complete_task']);
  $config->save();
}
