<?php

/**
 * @file
 * Contains bc_webform.module.
 */

use \Drupal\bc_webform\BcWebformHandler;
use \Drupal\Core\Session\AccountInterface;
use \Drupal\Core\Access\AccessResult;
use \Drupal\webform\WebformInterface;
use \Drupal\webform\WebformSubmissionInterface;
use \Drupal\taxonomy\Entity\Term;
use \Drupal\Core\Form\FormStateInterface;

define('BC_WEBFORM_ROLES', serialize([
  '2mp_user' => '2mp_user',
  ]));

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function bc_webform_webform_submission_presave(WebformSubmissionInterface $webform_submission) {
  if (!bc_webform_has_anonymization($webform_submission->getWebform())) {
    return;
  }
  $bc_webform_handler = new BcWebformHandler($webform_submission->getWebform());
  $bc_webform_handler->registerUserSubmission($webform_submission->getOwnerId(), $webform_submission->getToken());
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function bc_webform_webform_access(WebformInterface $webform, $operation, AccountInterface $account) {
  if (in_array($operation, ['submission_page']) || $account->id() <= 1) {
    return AccessResult::neutral();
  }

  $bc_webform_handler = new BcWebformHandler($webform);
  if (!$bc_webform_handler->matchOrganization($account->id())) {
    return AccessResult::forbidden();
  }

  return AccessResult::neutral();
}

/**
 * Implements hook_form_alter().
 */
function bc_webform_form_alter(array &$form, FormStateInterface $form_state) {
  if (!empty($form_state->getBuildInfo()['base_form_id'])
    && strpos($form_state->getBuildInfo()['base_form_id'], 'webform_submission_') === 0) {
    bc_webform_webform_submission_custom_alter($form, $form_state);
  }
}

/**
 * Implements custom form alter.
 */
function bc_webform_webform_submission_custom_alter(array &$form, FormStateInterface $form_state) {
  /** @var WebformSubmissionInterface $webform_submission */
  $webform_submission = $form_state->getFormObject()->getEntity();
  if (!bc_webform_has_anonymization($webform_submission->getWebform())) {
    return;
  }
  $bc_webform_handler = new BcWebformHandler($webform_submission->getWebform());
  $messenger = \Drupal::service('messenger');

  if (!$bc_webform_handler->isAllowedSubmit($webform_submission->getOwnerId())
    || !$bc_webform_handler->matchOrganization($webform_submission->getOwnerId())
    ) {
    $messenger->addMessage(t("You don't have access to send submission for this form."), 'warning');
    $form['#disabled'] = TRUE;
  }

  if ($bc_webform_handler->userHasSubmittion($webform_submission->getOwnerId())) {
    $messenger = \Drupal::service('messenger');
    $messenger->addMessage('You already sent submission for this form.', 'warning');
    $form['#disabled'] = TRUE;
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function bc_webform_form_webform_results_clear_alter(array &$form, FormStateInterface $form_state) {
  $form['#submit'][] = 'bc_werform_results_clear_submit';
}

function bc_werform_results_clear_submit(array $form, FormStateInterface $form_state) {
  /** @var WebformInterface $webform */
  list($webform, $sourceEntity) = \Drupal::service('webform.request')->getWebformEntities();
  if (!bc_webform_has_anonymization($webform)) {
    return;
  }
  $bc_webform_handler = new BcWebformHandler($webform);
  $bc_webform_handler->resetSubmissions();
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * Altering general webform settings.
 */
function bc_webform_form_webform_form_alter(array &$form, FormStateInterface $form_state) {
  if (!in_array($form['#form_id'], ['webform_add_form', 'webform_settings_form'])) {
    return;
  }

  /** @var WebformInterface $webform */
  $webform = $form_state->getFormObject()->getEntity();
  $available_roles = \Drupal::entityTypeManager()->getStorage('user_role')->loadMultiple();
  $roles = $webform->getThirdPartySetting('bc_webform', 'roles', unserialize(BC_WEBFORM_ROLES));
  $form['bc_webform'] = [
    '#type' => 'details',
    '#title' => t('Bellcom webform settings'),
    '#weight' => 4,
    '#open' => TRUE,
    '#collapsible' => TRUE,
    '#tree' => TRUE,
  ];

  $options = [];
  foreach ($available_roles as $role) {
    if (strpos($role->id(), '2mp') === FALSE) {
      continue;
    }
    $options[$role->id()] = $role->label();
  }
  $form['bc_webform']['roles'] = [
    '#type' => 'checkboxes',
    '#title' => t('Roles that allowed send submissions'),
    '#options' => $options,
    '#default_value' => $roles,
  ];

  $user = $webform->getOwner();
  $values = $user->get('field_organisation')->getValue();
  $user_organization_tid = $webform->getThirdPartySetting('bc_webform', 'organisation_tid');
  $options = [];
  foreach ($values as $value) {
    $options[$value['target_id']] = Term::load($value['target_id'])->name->value;
  }
  $form['bc_webform']['organisation_tid'] = [
    '#type' => 'select',
    '#options' => $options,
    '#title' => t('Organisation'),
    '#default_value' => empty($user_organization_tid) ? NULL : $user_organization_tid,
  ];

  if (!bc_webform_has_anonymization($webform)) {
    $form['bc_webform']['anonymization'] = [
      '#type' => 'checkbox',
      '#title' => t('Add submission anonymization'),
      '#default_value' => TRUE,
    ];
  }

  $form['actions']['submit']['#submit'][] = 'bc_webform_webform_form_submit';
}

/**
 * Custom form submission handler for 'webform_settings_form'.
 *
 * Saving general webform settings.
 */
function bc_webform_webform_form_submit(array $form, FormStateInterface $form_state) {
  $webform = $form_state->getFormObject()->getEntity();
  $settings = &$form_state->getValue('bc_webform');
  $webform->setThirdPartySetting('bc_webform', 'roles', array_filter($settings['roles']));
  $webform->setThirdPartySetting('bc_webform', 'organisation_tid', $settings['organisation_tid']);

  if ($settings['anonymization'] && !bc_webform_has_anonymization($webform)) {
    /** @var \Drupal\webform\Plugin\WebformHandlerManagerInterface $handler_manager */
    $handler_manager = \Drupal::service('plugin.manager.webform.handler');

    // Create webform handler.
    $handler_configuration = [
      'id' => 'anonymous_submission',
      'label' => 'Anonymous submission',
      'handler_id' => 'anonymous_submission',
      'status' => 1,
      'weight' => 0,
      'settings' => [],
    ];
    $handler = $handler_manager->createInstance('anonymous_submission', $handler_configuration);

    // Must set original id so that the webform can be resaved.
    $webform->setOriginalId($webform->id());

    // Add webform handler which triggers Webform::save().
    $webform->addWebformHandler($handler);
  }
  $webform->save();
}

/**
 * Checks if webform use AnonymousSubmission Handler.
 *
 * @param WebformInterface $webform
 *
 * @return mixed
 */
function bc_webform_has_anonymization(WebformInterface $webform) {
  $handlers = $webform->getHandlers();
  if ($handlers->has('anonymous_submission')
    && $handlers->get('anonymous_submission')->getStatus()
  ) {
    return TRUE;
  }
}
