<?php

/**
 * @file
 * Contains bc_2movepeople_wpm.module.
 */

use \Drupal\user\Entity\User;
use \Drupal\Core\Entity\EntityInterface;
use \Drupal\web_push_notification\Entity\SubscriptionInterface;

/**
 * Implements hook_page_attachments_alter().
 *
 * Adds user uuid to webPushNotification context.
 */
function bc_2movepeople_wpn_page_attachments_alter(array &$attachments) {
  if (empty($attachments['#attached']['drupalSettings']['webPushNotification'])
    || \Drupal::currentUser()->isAnonymous()) {
    return;
  }

  $attachments['#attached']['drupalSettings']['webPushNotification']['context'] = [
    'uuid' => User::load(\Drupal::currentUser()->id())->uuid(),
  ];
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function bc_2movepeople_wpn_wpn_subscription_insert(EntityInterface $entity) {
  if ($entity instanceof SubscriptionInterface) {
    $logger = \Drupal::service('logger.channel.default');
    $context_json = (string) \Drupal::request()->get('context');
    $context = (array) json_decode($context_json);
    if (empty($context['uuid'])) {
      $logger->warning('No uuid send in context or context is wrong.');
      return;
    }

    $result = \Drupal::entityTypeManager()->getStorage('user')->loadByProperties(['uuid' => $context['uuid']]);
    if (!empty($result)) {
      $user = reset($result);
      $user->field_wpn->appendItem($entity);
      $user->save();
    }
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function bc_2movepeople_wpn_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'page_attachments_alter') {
    // Move our hook_page_attachments_alter() implementation to the end of the list.
    $group = $implementations['bc_2movepeople_wpn'];
    unset($implementations['bc_2movepeople_wpn']);
    $implementations['bc_2movepeople_wpn'] = $group;
  }
}
