<?php

/**
 * @file
 * Contains bc_2movepeople.module..
 */

use Drupal\Core\Url;

/**
 * Implements hook_toolbar().
 */
function bc_2movepeople_toolbar(&$items) {
  $items = array();

// List all possible modules. 

  $bc_modules = array(
    'bc_2movepeople_dashboard' => 'bc_2movepeople_dashboard.user.progressions',
  );

  
// Add a link to enable all examples.
  $links = array();
  $links['bc_2movepeople_dashboard'] = array(
    'title' => t('Dashboard'),
    'url' => Url::fromRoute('bc_2movepeople_dashboard'),
    'options' => array(
      'title' => t('Go to the system dashboard.'),
    ),
  );

  $links['bc_2movepeople_user'] = array(
    'title' => t('Account'),
    'url' => Url::fromuri('internal:/user'),
    'options' => array(
      'title' => t('Go to the user account.'),
    ),
  );/*
  $links['administration'] = array(
    'title' => t('Administration'),
    'url' => Url::fromRoute('administration'),
    'options' => array(
      'title' => t('Go to the administratin.'),
    ),
  );*/
  $links['bc_2movepeople_questionmaker'] = array(
    'title' => t('QuestionMaker'),
    'url' => Url::fromRoute('bc_2movepeople_questionmaker'),
    'options' => array(
      'title' => t('Go to the Questionmaker.'),
    ),
  );/*
  $links['progressions'] = array(
    'title' => t('Progressions'),
    'url' => Url::fromRoute('progresssions'),
    'options' => array(
      'title' => t('Go to the Progressions.'),
    ),
  );
  $links['userlist'] = array(
    'title' => t('User List'),
    'url' => Url::fromRoute('userlist'),
    'options' => array(
      'title' => t('Go to the User Management List.'),
    ),
  );*/
  $links['bc_2movepeople_admin_settings_form'] = array(
    'title' => t('Admin Settings'),
    'url' => Url::fromRoute('bc_2movepeople_admin_settings_form'),
    'options' => array(
      'title' => t('Go to the Module Settings.'),
    ),
  );
  $items['2movepeople'] = array(
    '#type' => 'toolbar_item',
    'tab' => array(
      '#type' => 'link',
      '#title' => t('2MovePeople'),
      // @todo: Once it is created, use the example index page.
      '#url' => Url::fromRoute('<front>'),
      '#attributes' => array(
        'title' => t('2 Move People - it matters'),
        'class' => array('toolbar-icon', 'toolbar-icon-examples'),
      ),
    ),
    'tray' => array(
      '#heading' => t('2movepeople app'),
      'shortcuts' => array(
        '#theme' => 'links__toolbar_2movepeople',
        '#links' => $links,
        '#attributes' => array(
          'class' => array('toolbar-menu'),
        ),
      ),
    ),
    '#attached' => array(
      'library' => array(
        array('commerce', 'ecommerce.icons'),
      ),
    ),
  );


  return $items;
}


use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bc_2movepeople_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bc_2movepeople module.
    case 'help.page.bc_2movepeople':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('2movepeopel settings') . '</p>';
      return $output;

    default:
  }
}
